apiVersion: apps/v1     
kind: Deployment
metatdata:
  name: mysql-db    
  metadata: web-ns
spec:
  selector:
    matchLabels:
      app: mysql-db     #Day la deployment cua deployment Mysql 
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        ports:
          - containerPort: 3306
        env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: pet
        volumeMounts:
          - name: mysql-data
            mountPath: /docker-entrypoint-initdb.d/pet.sql
      volumes:
      - name: mysql-data
        hostPath:
        path: ./pet.sql

---
apiVersion: v1      
kind: Service
metadata:
  name: mysql-service #Day la service cua deployment MYSQL
  namespace: web-ns
spec:
  selector:
    name: mysql-db
  ports:
    - port: 3306    #Cong 3306
  type: LoadBalancer
