apiVersion: apps/v1
kind: Deployment
metatdata:
  name: phpmyadmin
  metadata: web-ns #Day la deloyment cua phpmyadmin 
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.2
        ports:
           - containerPort: 8081
        env:
            - name: PMA_HOST
              value: mysql-service
            - name: MYSQL_ROOT_PASSWORD
              value: root
        resources:
          limits:
            cpu: "0.5"  # CPU limit
            memory: "512Mi"  # Memory limit

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc    #Day la service cua phpmyadmin
  namespace: web-ns
spec:
  selector:
    name: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
